[build]
  publish = "."

[[headers]]
  for = "/*.csv"
  [headers.values]
    Content-Type = "text/csv"
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/data/index.json"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=3600"
